"""table name

Revision ID: 030fbc3e31d7
Revises: 1636fcd23598
Create Date: 2021-03-15 20:47:11.950346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030fbc3e31d7'
down_revision = '1636fcd23598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('millesime', sa.Integer(), nullable=True),
    sa.Column('code_archet', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('producer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=128), nullable=True),
    sa.Column('millesime', sa.INTEGER(), nullable=True),
    sa.Column('code_archet', sa.VARCHAR(length=10), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('producer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product')
    # ### end Alembic commands ###
